### ISSUE TITLE
Reintegrate bug fixes from fork

### ISSUE THREAD

**Issue by rfahlberg** [ansys/pyoptislang#114]
### 🐞 Description of the bug

Please reintegrate bug fixes from fork at [Solution-Applications/pyoptislang](https://github.com/Solution-Applications/pyoptislang).

### 📝 Steps to reproduce

n/a

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

n/a

### 🐍 Which Python version are you using?

3.7

### 📦 Installed packages

```shell
n/a
```

**Comment by rfahlberg** [comment]
@PanekOndrej Please process with highest priority.

**Comment by PanekOndrej** [comment]
This should be solved in https://github.com/pyansys/pyoptislang/pull/115

We could provide some of these queries for common user in `Node` or `Project` classes, another issue may be created from ideas below: 

``Node`` class: 
- add `get_states()` method
- change `get_status()` method (extract info about status from `get_actor_status_info` instead of more detail `get_actor_info`)
- get_actor_supports() method
  -  enumeration/list of valid features? e. g. { "What": "ACTOR_SUPPORTS", "uid": "5cdfb20b-bef6-4412-9985-89f5ded5ee95","args": { "feature": "CAN_FINALIZE" } } 
- get_available_input_slots() & output_slots() -> ???
  - either return str 
  - or create class `Slot` with properties `name` and  `value`
- get_used_input_slots() / output -> `Slot` or `str`
- get_slot_value(`Slot` or `str`)
