### ISSUE TITLE
Launch option for optislang_service.exe

### ISSUE THREAD

**Issue by optislangdeveloper** [ansys/pyoptislang#143]
### 📝 Description of the feature

The default optiSLang executable is currently optislang_batch.exe. For some use cases that make use of optiSLang node dialogs, it would be nice to have the option to launch also the optislang_service executable.

### 💡 Steps for implementing the feature

Currently there are two startup options: batch=True/False
I would like to see an extension to batch/service/gui 

See https://github.com/ansys/pyoptislang/blob/936b6b8a08d6e4da053412b9fdab7e8ea54853c9/src/ansys/optislang/core/osl_process.py#L652 

The command line argument would be --svc

**Comment by optislangdeveloper** [comment]
@rfahlberg FYI

**Comment by rfahlberg** [comment]
I back that.

**Comment by optislangdeveloper** [comment]
Good to know that this is already supported. 

I would still like to have a clear distinction, but for now at least an error should be thrown if service and batch are specified.

**Comment by PanekOndrej** [comment]
OK, let's agree that the `service` argument will be added to the constructor and it'll be checked whether not used in combination with `batch` argument. I would suggest not to check `additional_args` because there may be more incompatible options than `-svc` & `-b` and assume that whoever is using `additional_args` knows what they're doing.

**Comment by rfahlberg** [comment]
Agreed.

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________
